### ISSUE TITLE
Perfect. 👍

### ISSUE THREAD

**Issue by VisionR1** [reveny/Android-Native-Root-Detector#1]
Thanks for this app.
The new update, with info exactly what it detects, is awesome. 😎 

Only the logo have some issue, I see your profile image but over have and the android logo.
The same and older version.
I have Xiaomi Poco X3 NFC.

![IMG_20241114_175956](https://github.com/user-attachments/assets/2a0d51e9-6748-4098-aa5b-abd5bb25101e)

**Comment by reveny** [comment]
That logo is intended.

**Comment by VisionR1** [comment]
> That logo is intended.

Good to know, I thought some issue with my device.
So, all working perfect.👌
